"""
TidesDB Python Bindings

Official Python bindings for TidesDB v7+ - A high-performance embedded key-value storage engine.

Copyright (C) TidesDB
Licensed under the Mozilla Public License, v. 2.0
"""

from .tidesdb import (
    TidesDB,
    Transaction,
    Iterator,
    ColumnFamily,
    Config,
    ColumnFamilyConfig,
    ObjStoreConfig,
    ObjStoreBackend,
    Stats,
    CacheStats,
    DbStats,
    CompressionAlgorithm,
    SyncMode,
    LogLevel,
    IsolationLevel,
    TidesDBError,
    default_config,
    default_column_family_config,
    objstore_default_config,
    objstore_fs_create,
    objstore_s3_create,
    objstore_s3_create_config,
    save_config_to_ini,
    load_config_from_ini,
    init,
    finalize,
    raise_open_file_limit,
    compression_available,
    CommitOp,
    COMPARATOR_FUNC,
    COMMIT_HOOK_FUNC,
    TDB_SUCCESS,
    TDB_ERR_MEMORY,
    TDB_ERR_INVALID_ARGS,
    TDB_ERR_NOT_FOUND,
    TDB_ERR_IO,
    TDB_ERR_CORRUPTION,
    TDB_ERR_EXISTS,
    TDB_ERR_CONFLICT,
    TDB_ERR_TOO_LARGE,
    TDB_ERR_MEMORY_LIMIT,
    TDB_ERR_INVALID_DB,
    TDB_ERR_UNKNOWN,
    TDB_ERR_LOCKED,
    TDB_ERR_READONLY,
    TDB_ERR_BUSY,
)

__version__ = "0.11.1"
__all__ = [
    "TidesDB",
    "Transaction",
    "Iterator",
    "ColumnFamily",
    "Config",
    "ColumnFamilyConfig",
    "ObjStoreConfig",
    "ObjStoreBackend",
    "Stats",
    "CacheStats",
    "DbStats",
    "CompressionAlgorithm",
    "SyncMode",
    "LogLevel",
    "IsolationLevel",
    "TidesDBError",
    "default_config",
    "default_column_family_config",
    "objstore_default_config",
    "objstore_fs_create",
    "objstore_s3_create",
    "objstore_s3_create_config",
    "save_config_to_ini",
    "load_config_from_ini",
    "init",
    "finalize",
    "raise_open_file_limit",
    "compression_available",
    "CommitOp",
    "COMPARATOR_FUNC",
    "COMMIT_HOOK_FUNC",
    "TDB_SUCCESS",
    "TDB_ERR_MEMORY",
    "TDB_ERR_INVALID_ARGS",
    "TDB_ERR_NOT_FOUND",
    "TDB_ERR_IO",
    "TDB_ERR_CORRUPTION",
    "TDB_ERR_EXISTS",
    "TDB_ERR_CONFLICT",
    "TDB_ERR_TOO_LARGE",
    "TDB_ERR_MEMORY_LIMIT",
    "TDB_ERR_INVALID_DB",
    "TDB_ERR_UNKNOWN",
    "TDB_ERR_LOCKED",
    "TDB_ERR_READONLY",
    "TDB_ERR_BUSY",
]
